# Generated by Django 4.0.4 on 2022-05-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование коллекции')),
                ('image', models.ImageField(upload_to='collection', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание товара')),
                ('item_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Артикул')),
                ('old_price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('new_price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='О Товаре')),
                ('size_range', models.CharField(max_length=20, verbose_name='размерный ряд')),
                ('amount_in', models.PositiveIntegerField(default=0, verbose_name='количество в линейке')),
                ('compound', models.CharField(max_length=200, verbose_name='Состав Ткани')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('is_in_cart', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemimage', to='items.item')),
            ],
        ),
    ]
