# Generated by Django 4.0.4 on 2022-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата добавления'),
        ),
    ]
