# Generated by Django 4.0.4 on 2022-06-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие с условиями публичной оферты'),
        ),
    ]
