# Generated by Django 4.0.4 on 2022-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_in_cart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
