# Generated by Django 4.0.4 on 2022-05-23 12:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'фотографии товара', 'verbose_name_plural': 'фотографии товара'},
        ),
        migrations.AlterField(
            model_name='item',
            name='new_price',
            field=models.PositiveIntegerField(default=0, verbose_name='новая Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.PositiveIntegerField(default=0, verbose_name='старая Цена'),
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcolor', to='items.item')),
            ],
            options={
                'verbose_name': 'цвет товара',
                'verbose_name_plural': 'цвет товара',
            },
        ),
    ]
