# Generated by Django 4.0.4 on 2022-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_in_favourite_alter_item_is_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bestseller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='novelty',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
