# Generated by Django 4.0.4 on 2022-05-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_bestseller_item_novelty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bestseller',
            new_name='is_bestseller',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='novelty',
            new_name='is_novelty',
        ),
    ]
