# Generated by Django 4.0.4 on 2022-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_order_rename_new_price_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='новая Цена'),
        ),
    ]
