# Generated by Django 4.0.4 on 2022-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_searchhelper'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='amount_item',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='количество товаров'),
        ),
        migrations.AlterField(
            model_name='itemcart',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество линеек'),
        ),
    ]
