# Generated by Django 4.0.4 on 2022-05-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemCart',
        ),
    ]
