# Generated by Django 4.0.4 on 2022-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemcart_amount_item_alter_itemcart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_range',
            field=models.CharField(max_length=5, verbose_name='размерный ряд'),
        ),
    ]
