# Generated by Django 4.0.4 on 2022-06-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemcart_image_alter_itemcart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_after_discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_before_discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sum_of_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='item_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='line_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество линеек'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_after_discount',
            field=models.IntegerField(default=0, verbose_name='Общая цена со скидкой'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_before_discount',
            field=models.IntegerField(default=0, verbose_name='Общая цена без скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_of_discount',
            field=models.IntegerField(default=0, verbose_name='сумма скидки'),
        ),
    ]
