# Generated by Django 4.0.4 on 2022-06-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_orderitem_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
    ]
