# Generated by Django 4.0.4 on 2022-06-02 10:29

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_size_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size_range',
            field=models.CharField(max_length=5, validators=[items.models.validate_slash], verbose_name='размерный ряд'),
        ),
    ]
