# Generated by Django 4.0.4 on 2022-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_is_novelty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_bestseller',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='хит продаж?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_in_favourite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='избранное?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_novelty',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='новинка?'),
        ),
    ]
