# Generated by Django 4.0.4 on 2022-05-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_orderitem_itemcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcollection', to='items.collection', verbose_name='Коллекция'),
        ),
    ]
