# Generated by Django 4.0.4 on 2022-06-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_amount_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhelper',
            options={'verbose_name': 'Поисковой помощник', 'verbose_name_plural': 'Поисковой помощник'},
        ),
        migrations.AddField(
            model_name='itemcart',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemimagecolor', verbose_name='цвет'),
        ),
    ]
