# Generated by Django 4.0.4 on 2022-06-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_searchhelper_options_itemcart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('NEW', 'НОВЫЙ'), ('FRAMED', 'ОФОРМЛЕН'), ('CANCELED', 'ОТМЕНЕН')], default='NEW', max_length=12, null=True, verbose_name='статус заказа'),
        ),
    ]
