# Generated by Django 4.0.4 on 2022-06-07 09:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='О нас')),
                ('image_1', models.ImageField(upload_to='about')),
                ('image_2', models.ImageField(upload_to='about')),
                ('image_3', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='advantages', verbose_name='Иконка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши Преимущества',
                'verbose_name_plural': 'Наши Преимущества',
            },
        ),
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('reason', models.CharField(default='обратный звонок', max_length=200, verbose_name='тип обращения')),
                ('call_status', models.CharField(choices=[('YES', 'ДА'), ('NO', 'НЕТ')], default='NO', max_length=3, verbose_name='статус звонка')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(upload_to='header')),
                ('footer', models.ImageField(upload_to='footer')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('phone_number_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона 2')),
                ('whatsapp_link', models.CharField(max_length=200, verbose_name='Ссылка на вотсап')),
                ('telegram_link', models.CharField(max_length=200, verbose_name='Ссылка на телеграмм')),
                ('instagram_link', models.CharField(max_length=200, verbose_name='Ссылка на инстаграмм')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Помощь',
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='HelpIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='help')),
            ],
            options={
                'verbose_name': 'Иконка для помощи',
                'verbose_name_plural': 'Иконка для помощи',
            },
        ),
        migrations.CreateModel(
            name='MainPageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='mainpage', verbose_name='Иконка')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Фото для главной страницы',
                'verbose_name_plural': 'Фото для главной страницы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Публичная оферта', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Публичная Оферта',
                'verbose_name_plural': 'Публичная Оферта',
            },
        ),
    ]
