# Generated by Django 4.0.4 on 2022-06-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='instagram_link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на инстаграмм'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram_link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на телеграмм'),
        ),
    ]
