# Generated by Django 4.0.4 on 2022-05-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='help')),
                ('help', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='info.help')),
            ],
        ),
    ]
