# Generated by Django 4.0.4 on 2022-05-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_helpicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpicon',
            name='help',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='helpicon', to='info.help'),
        ),
    ]
