# Generated by Django 4.0.4 on 2022-06-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_contacts_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpicon',
            name='help',
        ),
    ]
