# Generated by Django 4.0.4 on 2022-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_offer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='advantages', verbose_name='Иконка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши Преимущества',
                'verbose_name_plural': 'Наши Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tech', models.CharField(max_length=200, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Телефонный номер')),
                ('phone_number_2', models.CharField(max_length=200, verbose_name='Телефонный номер 2')),
                ('whatsapp_link', models.CharField(max_length=200, verbose_name='Ссылка на вотсап')),
                ('telegram_link', models.CharField(max_length=200, verbose_name='Ссылка на вотсап')),
                ('instagram_link', models.CharField(max_length=200, verbose_name='Ссылка на вотсап')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='MainPageIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='mainpage', verbose_name='Иконка')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Фото для главной страницы',
                'verbose_name_plural': 'Фото для главной страницы',
            },
        ),
    ]
