# Generated by Django 4.0.4 on 2022-06-13 12:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_help_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderFooterPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(upload_to='header')),
                ('footer', models.ImageField(upload_to='footer')),
                ('title', models.CharField(default='Публичная оферта', max_length=200, verbose_name='Заголовок')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='header',
        ),
    ]
