# Generated by Django 4.0.4 on 2022-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_headerfooterpic_remove_contacts_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooterpic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
