# Generated by Django 4.0.4 on 2022-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_helpicon_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='reason',
            field=models.CharField(default='обратный звонок', max_length=200, verbose_name='тип обращения'),
        ),
    ]
