# Generated by Django 4.0.4 on 2022-06-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_callback_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpicon',
            options={'verbose_name': 'Иконка для помощи', 'verbose_name_plural': 'Иконка для помощи'},
        ),
    ]
